name: Enviar lembretes WhatsApp

on:
  schedule:
    # Rodar todo dia às 10h UTC (7h Brasília)
    - cron: '0 10 * * *'
    # Rodar todo dia às 22h UTC (19h Brasília)
    - cron: '0 22 * * *'
  workflow_dispatch: 

jobs:
  enviar-mensagem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          TWILIO_WHATSAPP_TO: ${{ secrets.TWILIO_WHATSAPP_TO }}
        run: node index.js
